CREATE TABLE IF NOT EXISTS chores (
	id CHAR(10) PRIMARY KEY CHECK (id != '') NOT NULL,
   	name TEXT NOT NULL UNIQUE CHECK (name != ''),
    description TEXT,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	modified_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);