{{- $secretName := .Values.secretName | default (printf "%s-pg-conn" (include "whodidthechores.fullname" .)) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whodidthechores.fullname" . }}
  labels: {{- include "whodidthechores.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  selector:
    matchLabels: {{- include "whodidthechores.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels: {{- include "whodidthechores.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName | quote }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "whodidthechores.serviceAccountName" . }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      containers:
        - name: whodidthechores
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if (.Values.resources.limits).cpu }}
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            {{- end }}
            {{- if (.Values.resources.limits).memory }}
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
            {{- end }}
            - name: WDTC_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName | quote }}
                  key: "username"
            - name: WDTC_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName | quote }}
                  key: "password"
            - name: WDTC_DATABASE_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName | quote }}
                  key: "host"
            - name: WDTC_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName | quote }}
                  key: "port"
            - name: WDTC_DATABASE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName | quote }}
                  key: "database"
            - name: WDTC_PORT
              value: {{ .Values.containerPorts.http | quote}}
            - name: WDTC_TIMEZONE
              value: {{ .Values.whoDidTheChores.timezone | quote}}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
              {{- if .Values.hostNetwork }}
              hostPort: {{ .Values.containerPorts.http }}
              {{- else if .Values.hostPorts.http }}
              hostPort: {{ .Values.hostPorts.http }}
              {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe: {{- toYaml (omit .Values.startupProbe "enabled") | nindent 12 }}
            tcpSocket:
              port: http
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.additionalVolumeMounts }}
              {{- toYaml .Values.additionalVolumeMounts | nindent 12 }}
            {{- end }}
            - mountPath: /tmp
              name: tmp
      volumes:
      {{- if .Values.additionalVolumes }}
        {{- toYaml .Values.additionalVolumes | nindent 8 }}
      {{- end }}
        - name: tmp
          emptyDir: {}
